### ISSUE TITLE
Dependency `jaeger-client` overrides client requirement

### ISSUE THREAD

**Issue by itsofirk** [kube-HPC/python-wrapper.hkube#40]
Python-wrapper.hkube requires in its setup file the `jaeger-client== 4` package.
This package depends on `tornado>=4.3,<5`
My code requires `tornado>5`, which breaks the prior versions api.
Therefore, when my code overrides the wrapper's dependency, it prevents hkube from initializing a container on k8s.

I suggest changing the requirement in python-wrapper's setup.py file from `jaeger-client==4` to `>=4.3.0` and by that being up-to-date with the changes they made.

Python-wrapper.hkube - [setup.py](https://github.com/kube-HPC/python-wrapper.hkube/blob/master/setup.py)
Jaeger-client 4.3.0 - [setup.py](https://github.com/jaegertracing/jaeger-client-python/blob/4.3.0/setup.py)
Jaeger-client 4.0.0 - [setup.py](https://github.com/jaegertracing/jaeger-client-python/blob/4.0.0/setup.py)
[Changes log](https://github.com/jaegertracing/jaeger-client-python/compare/4.0.0...jaegertracing:4.3.0#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7)

Tornado 4.0 - Has the function engine() - [tornado/gen.py](https://github.com/tornadoweb/tornado/blob/branch4.0/tornado/gen.py)
Tornado 6.1 - Latest - engine() function removed - [tornado/gen.py](https://github.com/tornadoweb/tornado/blob/branch6.1/tornado/gen.py)

**Comment by yehiyam** [comment]
@itsofirk Thanks.
We need to test with the newer version. If everything is ok, we will create the update

**Comment by yehiyam** [comment]
Closing this issue in favor of kube-HPC/hkube#1045
